[workspace]
resolver = "3"

members = [
    "crates/maclean-types",
    "crates/maclean-core",
    "crates/maclean-storage",
    "crates/maclean-platform",
    "crates/maclean-cli",
    "apps/maclean-free",
]

default-members = [
    "apps/maclean-free",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/jamesfeng2009/maclean"
